apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-hook-pre-cm
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
data:
  helloWorld: "Hello my friend!"